<?php
/**
 * @file
 * Custom functions for Views Bootstrap.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\dardev_careers\ViewsNews;
use Drupal\views\ViewExecutable;
/**
 * Implements hook_theme().
 */
function dardev_careers_theme() {
  return ViewsCareers::getThemeHooks();
}



function dardev_careers_views_pre_render(ViewExecutable $view) {

  if (isset($view) && ($view->style_plugin->definition['id'] == 'views_careers_page')){
    
    $view->element['#attached']['library'][] = 'dardev_careers/dardev_careers';
    }
  
}
/*
* Implements hook_preprocess_HOOK() for views_view_unformatted template.
*/
function dardev_careers_preprocess(&$variables) {
 $variables['lang'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
 $lang_code         = \Drupal::languageManager()->getCurrentLanguage()->getId();
}